spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN